# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170223_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='dfad', max_length=50),
            preserve_default=False,
        ),
    ]
