# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170228_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default='nobody', max_length=50),
            preserve_default=False,
        ),
    ]
